In [1]:
import torch

##### Example 1

In [5]:
rewards = torch.tensor([1, 2, 3, 4])

In [47]:
import torch

Given `rewards` is the list of all predicted rewards from the current time step `0` to the next time step `3`

In [48]:
rewards

tensor([1, 2, 3, 4])

Write a function to calcualte the discounted reward at each time step

In [49]:
discount_factor = 0.99

In [50]:
def discount_reward(rewards, discount_factor):
    n_rewards = len(rewards)
    timesteps = torch.arange(0, n_rewards)
    
    # calculate the discount for each time step
    discount = torch.pow(discount_factor, timesteps)
    discounted_rewards = discount * rewards

    return discounted_rewards

In [51]:
discount_reward(rewards, discount_factor)

tensor([1.0000, 1.9800, 2.9403, 3.8812])

In [38]:
discount_reward(rewards, discount_factor)

tensor([1.0000, 1.9800, 2.9403, 3.8812])