<!-- WARNING: THIS FILE WAS AUTOGENERATED! DO NOT EDIT! -->

### Discounted Rewards

In [1]:
#| echo: false
#| output: asis
show_doc(discount_rewards)

---

[source](https://github.com/xrsrke/reinforcement-learning/blob/main/octopus/policy/reward.py#L11){target="_blank" style="float:right; font-size:smaller"}

### discount_rewards

>      discount_rewards (rewards, discount_factor)

In [ ]:
rewards = torch.tensor([0, 1, 2, 3, 4, 5])

Calculate the discounted return of a timestep

In [ ]:
rewards

tensor([0, 1, 2, 3, 4, 5])

### Discounted Return

In [2]:
#| echo: false
#| output: asis
show_doc(calculate_discounted_return_time_step)

---

[source](https://github.com/xrsrke/reinforcement-learning/blob/main/octopus/policy/reward.py#L25){target="_blank" style="float:right; font-size:smaller"}

### calculate_discounted_return_time_step

>      calculate_discounted_return_time_step (rewards, timestep,
>                                             discount_factor)

In [3]:
#| echo: false
#| output: asis
show_doc(test_hello)

---

[source](https://github.com/xrsrke/reinforcement-learning/blob/main/octopus/policy/reward.py#L34){target="_blank" style="float:right; font-size:smaller"}

### test_hello

>      test_hello ()

In [ ]:
calculate_discounted_return_time_step(rewards, timestep=2, discount_factor=0.99)

tensor([13.7419])

In [4]:
#| echo: false
#| output: asis
show_doc(calculate_discounted_return_each_timestep)

---

[source](https://github.com/xrsrke/reinforcement-learning/blob/main/octopus/policy/reward.py#L38){target="_blank" style="float:right; font-size:smaller"}

### calculate_discounted_return_each_timestep

>      calculate_discounted_return_each_timestep (rewards, discount_factor)

In [ ]:
rewards = [torch.tensor(5), torch.tensor(2), torch.tensor(3), torch.tensor(4)]

In [ ]:
calculate_discounted_return_each_timestep(rewards, discount_factor=0.99)

tensor([13.8015,  8.8904,  6.9600,  4.0000])

In [5]:
#| echo: false
#| output: asis
show_doc(calculate_discounted_return_an_episode)

---

[source](https://github.com/xrsrke/reinforcement-learning/blob/main/octopus/policy/reward.py#L53){target="_blank" style="float:right; font-size:smaller"}

### calculate_discounted_return_an_episode

>      calculate_discounted_return_an_episode (rewards, discount_factor=0.99)

In [ ]:
rewards = torch.tensor([0, 1, 2, 3, 4, 5])

In [ ]:
calculate_discounted_return_an_episode(rewards)

[tensor([14.4584]),
 tensor([14.6045]),
 tensor([13.7419]),
 tensor([11.8605]),
 tensor([8.9500]),
 tensor([5.])]

In [ ]:
def update_policy(rewards):
    discount_factor = 0.99
    discounted_rewards = []
    n_rewards = len(rewards)


    for t in range(n_rewards):
        Gt = 0 
        pw = 0
        for r in rewards[t:]:
            Gt = Gt + discount_factor**pw * r
            pw = pw + 1
        discounted_rewards.append(Gt)
    
    return discounted_rewards

In [ ]:
update_policy(rewards)

[tensor(14.4584),
 tensor(14.6045),
 tensor(13.7419),
 tensor(11.8605),
 tensor(8.9500),
 tensor(5.)]