# Rewards

> Fill in a module description here

In [32]:
#| default_exp nn.policy.rewards

In [33]:
#| hide
from nbdev.showdoc import *

In [34]:
#| hide
import nbdev; nbdev.nbdev_export()

In [35]:
#| export
import torch

### Discounted Rewards

In [36]:
#| export
def discount_rewards(rewards, discount_factor):
    n_rewards = len(rewards)
    timesteps = torch.arange(0, n_rewards)
    
    # calculate the discount for each time step
    discounts = torch.pow(discount_factor, timesteps)
    discounted_rewards = discounts * rewards
    
    # normalize
    discounted_rewards /= discounted_rewards.max()

    return discounted_rewards

In [37]:
rewards = torch.tensor([1, 2, 3, 4, 5])

Calculate the discounted return of a timestep

In [38]:
rewards

tensor([1, 2, 3, 4, 5])

In [46]:
#| export
def calculate_discounted_return(rewards, timestep, discount_factor):
    discounted_return = torch.zeros(1)
    for i, reward in enumerate(rewards[timestep:]):
        discounted_return += (discount_factor ** i) * reward
    
    return discounted_return

In [48]:
calculate_discounted_return(rewards, timestep=1, discount_factor=0.99)

tensor([13.7419])

In [50]:
#| export
def calculate_discounted_return_an_episode(rewards, discount_factor=0.99):
    total_returns = torch.zeros(1)
    discounted_returns = []
        
    for timestep in range(len(rewards)):
        discounted_return = calculate_discounted_return(rewards, timestep=timestep, discount_factor=discount_factor)
        discounted_returns.append(discounted_return)
    
    return discounted_returns

In [51]:
calculate_discounted_return_an_episode(rewards)

[tensor([14.6045]),
 tensor([13.7419]),
 tensor([11.8605]),
 tensor([8.9500]),
 tensor([5.])]