# Rewards

> Fill in a module description here

In [ ]:
#| default_exp policy.reward

In [ ]:
#| hide
from nbdev.showdoc import *

In [ ]:
#| hide
import nbdev; nbdev.nbdev_export()

In [ ]:
#| export
import torch

### Discounted Rewards

In [ ]:
#| export
def discount_rewards(rewards, discount_factor):
    n_rewards = len(rewards)
    timesteps = torch.arange(0, n_rewards)
    
    # calculate the discount for each time step
    discounts = torch.pow(discount_factor, timesteps)
    discounted_rewards = discounts * rewards
    
    # normalize
    discounted_rewards /= discounted_rewards.max()

    return discounted_rewards

In [ ]:
rewards = torch.tensor([0, 1, 2, 3, 4, 5])

Calculate the discounted return of a timestep

In [ ]:
rewards

tensor([0, 1, 2, 3, 4, 5])

### Discounted Return

In [ ]:
#| export
def calculate_discounted_return_time_step(rewards, timestep, discount_factor):
    discounted_return = torch.zeros(1)
    current_and_future_rewards = rewards[timestep:]
    for i, reward in enumerate(current_and_future_rewards):
        discounted_return += (discount_factor ** i) * reward
    
    return discounted_return

In [ ]:
#| export
def test_hello():
    pass

In [ ]:
calculate_discounted_return_time_step(rewards, timestep=2, discount_factor=0.99)

tensor([13.7419])

In [ ]:
#| export
def calculate_discounted_return_each_timestep(rewards, discount_factor):
    n_reward = len(rewards)
    discounted_returns = torch.zeros(n_reward).float()
    
    for i in range(n_reward):
        discounted_return = 0
        
        for k, reward in enumerate(rewards[i:]):
            discounted_return += (discount_factor**k) * reward
        
        discounted_returns[i] = discounted_return
    
    return discounted_returns

In [ ]:
rewards = [torch.tensor(5), torch.tensor(2), torch.tensor(3), torch.tensor(4)]

In [ ]:
calculate_discounted_return_each_timestep(rewards, discount_factor=0.99)

tensor([13.8015,  8.8904,  6.9600,  4.0000])

In [ ]:
#| export
def calculate_discounted_return_an_episode(rewards, discount_factor=0.99):
    total_returns = torch.zeros(1)
    discounted_returns = []
        
    for timestep in range(len(rewards)):
        discounted_return = calculate_discounted_return_time_step(rewards, timestep=timestep, discount_factor=discount_factor)
        discounted_returns.append(discounted_return)
    
    return discounted_returns

In [ ]:
rewards = torch.tensor([0, 1, 2, 3, 4, 5])

In [ ]:
calculate_discounted_return_an_episode(rewards)

[tensor([14.4584]),
 tensor([14.6045]),
 tensor([13.7419]),
 tensor([11.8605]),
 tensor([8.9500]),
 tensor([5.])]

In [ ]:
def update_policy(rewards):
    discount_factor = 0.99
    discounted_rewards = []
    n_rewards = len(rewards)


    for t in range(n_rewards):
        Gt = 0 
        pw = 0
        for r in rewards[t:]:
            Gt = Gt + discount_factor**pw * r
            pw = pw + 1
        discounted_rewards.append(Gt)
    
    return discounted_rewards

In [ ]:
update_policy(rewards)

[tensor(14.4584),
 tensor(14.6045),
 tensor(13.7419),
 tensor(11.8605),
 tensor(8.9500),
 tensor(5.)]